spring.application.name=domus-api

# CONFIGURAÇÃO DO BANCO DE DADOS (SQL SERVER)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=domus_db;encrypt=true;trustServerCertificate=true;
# Peça ao Ervin (DevOps) o usuário e senha exatos do Docker local que ele configurou
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD:SenhaForteDomus123!}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# CONFIGURAÇÃO DO JPA / HIBERNATE (O Mapeamento)
# O "update" faz o Spring criar ou atualizar as tabelas automaticamente baseado no seu código Java!
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring está gerando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURAÇÃO DE SEGURANÇA (JWT)
# O Spring vai procurar uma variável no computador/servidor chamada JWT_SECRET.
# O texto após os dois-pontos (minha_chave_local_123) é um valor "padrão" 
# que será usado só na sua máquina de desenvolvimento caso a variável não exista.
api.security.token.secret=${JWT_SECRET:minha_chave_local_123}