spring.application.name=domus-api

# CONFIGURAÇÃO DO BANCO DE DADOS (SQL SERVER)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# CONFIGURAÇÃO DO JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
